apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dynamic
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ceph.com/rbd
reclaimPolicy: Delete
parameters:
  monitors: 10.10.10.10:6789
  adminId: admin
  adminSecretName: ceph-secret1
  pool: kube
  userSecretName: ceph-secret-kube1 

