apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - 10.10.10.10:6789
    pool: kube
    image: ceph-image
    user: admin
    secretRef:
      name: ceph-secret1
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Delete

